#!/bin/bash
# skript vanuse määramine
#
echo "Sisestage palun oma vanus"
read vanus
if test $vanus -gt 0 -a $vanus -lt 11
then
	echo "Olete laps"
elif test $vanus -ge 11 -a $vanus -lt 18
then
	echo "Olete nooruk"
elif test $vanus -ge 18 -a $vanus -lt 63
then
	echo "Olete täiskasvanu"
elif test $vanus -ge 63
then
	echo "Olete senioor"
else
	echo "Mv sa ajad lohh"
fi
#
#lõpp

